// GENERATED by scripts/sync-entries.mjs — do not edit by hand.
// Add or remove a file in content/entries/, then run: npm run new:project
import type { EntryInput } from '../schema';

import agenticDevPipelines from './agentic-dev-pipelines';
import auc from './auc';
import brightskies from './brightskies';
import chessDigitization from './chess-digitization';
import concordia from './concordia';
import darwinz2022 from './darwinz-2022';
import darwinz2025 from './darwinz-2025';
import embeddedHomeAutomation from './embedded-home-automation';
import gamesAndApps from './games-and-apps';
import intellinote2 from './intellinote2';
import nirSpectroscopy from './nir-spectroscopy';
import projectCar from './project-car';
import qortova from './qortova';
import riscvCpu from './riscv-cpu';
import roboticsMechatronics from './robotics-mechatronics';
import telegramBot from './telegram-bot';
import transformerCnnStudy from './transformer-cnn-study';

export const entryInputs: EntryInput[] = [
  agenticDevPipelines,
  auc,
  brightskies,
  chessDigitization,
  concordia,
  darwinz2022,
  darwinz2025,
  embeddedHomeAutomation,
  gamesAndApps,
  intellinote2,
  nirSpectroscopy,
  projectCar,
  qortova,
  riscvCpu,
  roboticsMechatronics,
  telegramBot,
  transformerCnnStudy,
];
