#!/usr/bin/env node
/**
 * Regenerates content/entries/index.ts from the files in that directory.
 * Run it after adding or removing an entry file. `npm run new:project` calls it.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = join(process.cwd(), 'content', 'entries');

const camel = (id) => id.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const ids = readdirSync(DIR)
  .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
  .map((f) => f.replace(/\.ts$/, ''))
  .sort();

const imports = ids.map((id) => `import ${camel(id)} from './${id}';`).join('\n');
const list = ids.map((id) => `  ${camel(id)},`).join('\n');

writeFileSync(
  join(DIR, 'index.ts'),
  `// GENERATED by scripts/sync-entries.mjs — do not edit by hand.
// Add or remove a file in content/entries/, then run: npm run new:project
import type { EntryInput } from '../schema';

${imports}

export const entryInputs: EntryInput[] = [
${list}
];
`,
);

console.log(`Synced ${ids.length} entries into content/entries/index.ts`);
